export const BL_LABEL_DEFAULTS = {
  blLabelTitle: "BILL OF LADING",
  blLabelForwardingAgent: "Forwarding Agent:",
  blLabelShipper: "Shipper",
  blLabelBlNo: "B/L No.",
  blLabelReferenceNo: "Reference No.",
  blLabelCharterPartyDate: "Charter party dated on",
  blLabelConsignee: "Consignee",
  blLabelNotifyParty: "Notify party",
  blLabelFromMerchantRef: "From (for the Merchant reference)",
  blLabelPortOfLoading: "Port of Loading",
  blLabelFirstVessel: "First Vessel",
  blLabelVoyNo: "Voy.NO.",
  blLabelSecondVessel: "Second Vessel",
  blLabelPortOfTranshipment: "Port of Transhipment",
  blLabelPortOfDischarge: "Port of Discharge",
  blLabelTranshipmentTo: "For transhipment to (if transhipped at port of discharge)",
  blLabelFinalDestination: "Final Destination (for the Merchant reference)",
  blLabelMarksNumbers: "Marks & Numbers",
  blLabelPkgsKind: ": No. of pkgs. : Kind of packages; Description of goods",
  blLabelNoOfUnits: ": No. of Units : SAID TO BE",
  blLabelGrossWeightKgs: ": Gross weight kgs.",
  blLabelSaidToWeigh: ": SAID TO WEIGH",
  blLabelMeasurementM3: ": Measurement M3",
  blLabelSaidToMeasure: ": SAID TO MEASURE",
  blLabelKgs: "KGS",
  blLabelCbm: "CBM",
  blLabelFreightCharges: "Freight and charges",
  blLabelRevenueTons: "Revenue tons",
  blLabelRate: "Rate",
  blLabelPer: "per",
  blLabelPrepaid: "Prepaid",
  blLabelCollect: "Collect",
  blLabelTotalPackagesWords: "Total Number of packages or units(in words)",
  blLabelExRate: "Ex. Rate",
  blLabelDeclaredValue: "Declared value US$",
  blLabelFreightPrepaidAt: "Freight prepaid at",
  blLabelFreightPayableAt: "Freight payable at",
  blLabelPlaceDateIssue: "Place and date of issue",
  blLabelTotalPrepaidYen: "Total prepaid in Yen",
  blLabelNoOriginalBL: "No. of original B(s)/L",
} as const;

export type BlLabelKey = keyof typeof BL_LABEL_DEFAULTS;

export const BL_LABEL_FIELDS: { key: BlLabelKey; label: string }[] = [
  { key: "blLabelTitle", label: "Document Title Heading" },
  { key: "blLabelForwardingAgent", label: "\"Forwarding Agent:\" Heading" },
  { key: "blLabelShipper", label: "\"Shipper\" Heading" },
  { key: "blLabelBlNo", label: "\"B/L No.\" Heading" },
  { key: "blLabelReferenceNo", label: "\"Reference No.\" Heading" },
  { key: "blLabelCharterPartyDate", label: "\"Charter party dated on\" Heading" },
  { key: "blLabelConsignee", label: "\"Consignee\" Heading" },
  { key: "blLabelNotifyParty", label: "\"Notify party\" Heading" },
  { key: "blLabelFromMerchantRef", label: "\"From (for the Merchant reference)\" Heading" },
  { key: "blLabelPortOfLoading", label: "\"Port of Loading\" Heading" },
  { key: "blLabelFirstVessel", label: "\"First Vessel\" Heading" },
  { key: "blLabelVoyNo", label: "\"Voy.NO.\" Heading" },
  { key: "blLabelSecondVessel", label: "\"Second Vessel\" Heading" },
  { key: "blLabelPortOfTranshipment", label: "\"Port of Transhipment\" Heading" },
  { key: "blLabelPortOfDischarge", label: "\"Port of Discharge\" Heading" },
  { key: "blLabelTranshipmentTo", label: "\"For transhipment to\" Heading" },
  { key: "blLabelFinalDestination", label: "\"Final Destination\" Heading" },
  { key: "blLabelMarksNumbers", label: "\"Marks & Numbers\" Heading" },
  { key: "blLabelPkgsKind", label: "\"No. of pkgs / Kind of packages\" Heading" },
  { key: "blLabelNoOfUnits", label: "\"No. of Units : SAID TO BE\" Heading" },
  { key: "blLabelGrossWeightKgs", label: "\"Gross weight kgs.\" Heading" },
  { key: "blLabelSaidToWeigh", label: "\"SAID TO WEIGH\" Heading" },
  { key: "blLabelMeasurementM3", label: "\"Measurement M3\" Heading" },
  { key: "blLabelSaidToMeasure", label: "\"SAID TO MEASURE\" Heading" },
  { key: "blLabelKgs", label: "\"KGS\" Unit Label" },
  { key: "blLabelCbm", label: "\"CBM\" Unit Label" },
  { key: "blLabelFreightCharges", label: "\"Freight and charges\" Column Heading" },
  { key: "blLabelRevenueTons", label: "\"Revenue tons\" Column Heading" },
  { key: "blLabelRate", label: "\"Rate\" Column Heading" },
  { key: "blLabelPer", label: "\"per\" Column Heading" },
  { key: "blLabelPrepaid", label: "\"Prepaid\" Column Heading" },
  { key: "blLabelCollect", label: "\"Collect\" Column Heading" },
  { key: "blLabelTotalPackagesWords", label: "\"Total Number of packages or units (in words)\" Heading" },
  { key: "blLabelExRate", label: "\"Ex. Rate\" Heading" },
  { key: "blLabelDeclaredValue", label: "\"Declared value US$\" Heading" },
  { key: "blLabelFreightPrepaidAt", label: "\"Freight prepaid at\" Heading" },
  { key: "blLabelFreightPayableAt", label: "\"Freight payable at\" Heading" },
  { key: "blLabelPlaceDateIssue", label: "\"Place and date of issue\" Heading" },
  { key: "blLabelTotalPrepaidYen", label: "\"Total prepaid in Yen\" Heading" },
  { key: "blLabelNoOriginalBL", label: "\"No. of original B(s)/L\" Heading" },
];
